'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navigation
    'nav.pages': 'Halaman',
    'nav.features': 'Fitur',
    'nav.peerconnect': 'PeerConnect',
    'nav.aboutUs': 'Tentang Kami',
    'nav.login': 'Masuk',
    'nav.logout': 'Keluar',
    
    // Page titles
    'page.aiCampusGuide': 'AI Campus Guide',
    'page.eventRecommender': 'Event Recommender',
    'page.smartScheduleBuilder': 'Smart Schedule Builder',
    'page.peerConnectAI': 'Peer Connect AI',
    'page.smartTaskManager': 'Smart Task Manager',
    'page.projectCollaboration': 'Project Collaboration',
    
    // Hero Section
    'hero.empowering': 'Memberdayakan Mahasiswa dengan AI',
    'hero.companion': 'Teman Kampus Pintar Anda',
    'hero.navigate': 'Navigasi Kehidupan Kampus dengan Lancar',
    'hero.learn': 'Belajar Lebih Cerdas, Terhubung Lebih Baik, Raih Lebih Banyak',
    
    // Features Section
    'features.title': 'Fitur Unggulan Kami',
    'features.subtitle': 'Temukan berbagai fitur inovatif yang dirancang khusus untuk meningkatkan pengalaman kampus Anda',
    'features.aiCampusGuide': 'AI Campus Guide Chatbot',
    'features.aiCampusGuideDesc': 'Tanya apa saja tentang kampus! Dari cara mengisi KRS, lokasi gedung, info dosen, hingga prosedur beasiswa. AI siap membantu 24/7.',
    'features.eventRecommender': 'Event Recommender',
    'features.eventRecommenderDesc': 'Dapatkan rekomendasi kegiatan yang sesuai dengan minatmu! Seminar, lomba, UKM, volunteering - semua disesuaikan untukmu.',
    'features.smartSchedule': 'Smart Schedule Builder',
    'features.smartScheduleDesc': 'AI bantu atur jadwal kuliah dan kegiatanmu agar seimbang. Tidak ada lagi bentrok jadwal atau overload kegiatan!',
    'features.peerConnect': 'Peer Connect AI',
    'features.peerConnectDesc': 'Temukan teman atau mentor dengan minat yang sama! AI mencocokkan kamu dengan orang-orang yang tepat untuk berkembang bersama.',
    'features.taskManager': 'Smart Task Manager',
    'features.taskManagerDesc': 'Kelola tugas dan deadline dengan mudah! AI akan prioritaskan tugasmu dan ingatkan kamu sebelum terlambat.',
    'features.projectCollab': 'Project Collaboration',
    'features.projectCollabDesc': 'Kolaborasi project jadi lebih mudah! Buat tim, bagikan tugas, dan pantau progress bersama dalam satu platform.',
    
    // Stats
    'stats.activeStudents': 'Mahasiswa Aktif',
    'stats.eventsPerMonth': 'Event per Bulan',
    'stats.userSatisfaction': 'Kepuasan Pengguna',
    'stats.aiSupport': 'AI Support',
    
    // FAQ Section
    'faq.title': 'FAQs',
    'faq.welcome': 'Halo! Saya AI Assistant untuk aplikasi web AICAMPUS. Saya siap membantu menjawab pertanyaan seputar aplikasi AICAMPUS. Silakan pilih pertanyaan cepat di bawah atau ketik pertanyaan Anda sendiri!',
    'faq.q1': 'Apakah saya harus login untuk menggunakan fitur-fitur AICAMPUS?',
    'faq.a1': 'Ya, Anda perlu membuat akun dan login untuk menggunakan semua fitur AICAMPUS. Proses registrasi sangat mudah dan cepat - cukup gunakan email kampus Anda atau login dengan akun Google. Setelah login, Anda bisa langsung menikmati semua fitur seperti AI Campus Guide, Event Recommender, Smart Schedule Builder, dan lainnya.',
    'faq.q2': 'Bagaimana cara menggunakan fitur AI Campus Guide?',
    'faq.a2': 'Setelah login dan atur ptofile dimana Anda memasukan asal universtas atau bisa langsung masuk tanpa mengatur profile, klik page "AI Campus Guide" di dashboard. klik pertanyaan Anda tentang kampus atau bisa menannyakan selain yang ada pada pilihan di mode general, lalu AI akan memberikan jawaban yang akurat.',
    'faq.q3': 'Bagaimana cara menggunakan Smart Schedule Builder?',
    'faq.a3': 'Klik menu "Smart Schedule Builder", lalu masukkan mata kuliah dan kegiatan Anda dengan menekan tombol "Jadwal Kuliah" atau "Kegiatan Lain". Isi detail seperti nama, hari, dan waktu. Setelah selesai menambahkan semua jadwal, klik "Generate Jadwal Optimal" dan AI akan menyusun jadwal terbaik yang menghindari bentrok dan memaksimalkan waktu istirahat Anda. ini juga telah ter integrasi dengan google kalender.',
    'faq.q4': 'Bagaimana cara menggunakan Event Recommender?',
    'faq.a4': 'Buka menu "Event Recommender" di dashboard. Pertama kali, Anda di perlihatkan event event yang ada, tetapi apabila anda ingin mengikuti event tertentu maka anda dapat menggunakan filter yang ada di bagian sebelah kiri. Setelah itu, sistem akan otomatis merekomendasikan event yang sesuai. Anda bisa mendaftar langsung, atau melihat detail event seperti waktu, lokasi, dan persyaratan.',
    'faq.q5': 'Bagaimana cara menggunakan Peer Connect AI?',
    'faq.a5': 'Masuk ke menu "Peer Connect AI" dan lengkapi profil Anda (jurusan, minat, skills, tujuan). AI akan mencocokkan Anda dengan mahasiswa atau mentor yang compatible. Anda bisa melihat profil match, mengirim request connect, dan mulai berkomunikasi. Fitur ini sangat berguna untuk mencari study partner atau mentor untuk bimbingan karir juga dapat menggunakan video call.',
    'faq.q6': 'Bagaimana cara menggunakan Smart Task Manager?',
    'faq.a6': 'Buka menu "Smart Task Manager" dan tambahkan tugas-tugas Anda dengan deadline masing-masing. AI akan otomatis memprioritaskan tugas berdasarkan tingkat urgensi dan deadline. Anda akan mendapat notifikasi reminder sebelum deadline, dan bisa tracking progress tugas dalam satu dashboard yang mudah dipahami.',
    'faq.q7': 'Bagaimana cara menggunakan Project Collaboration?',
    'faq.a7': 'Klik "Project Collaboration", buat project baru, dan undang anggota tim Anda. Anda bisa assign task ke masing-masing anggota, upload file project, melakukan real-time collaboration, dan tracking progress project.',
    'faq.q8': 'Apakah AI Campus Guide bisa menjawab semua pertanyaan tentang kampus?',
    'faq.a8': 'Ya! AI Campus Guide kami dirancang untuk menjawab berbagai pertanyaan seputar kehidupan kampus, mulai dari cara mengisi KRS, lokasi gedung, info dosen, prosedur beasiswa, jadwal kuliah, hingga informasi UKM. AI kami terus belajar dan diperbarui untuk memberikan jawaban yang akurat dan relevan.',
    'faq.q9': 'Apakah data pribadi saya aman?',
    'faq.a9': 'Keamanan data Anda adalah prioritas utama kami. Semua informasi pribadi dienkripsi dan disimpan dengan standar keamanan tingkat enterprise. Kami tidak akan membagikan data Anda kepada pihak ketiga tanpa izin Anda. Platform kami juga mematuhi regulasi perlindungan data yang berlaku.',
    'faq.q10': 'Apakah layanan ini berbayar?',
    'faq.a10': 'Kami menyediakan paket gratis dengan fitur dasar yang sudah sangat lengkap untuk mendukung kehididupan kampus Anda. Untuk fitur premium seperti mentoring prioritas, analitik mendalam, dan rekomendasi yang lebih personal, tersedia paket berlangganan dengan harga terjangkau khusus untuk mahasiswa.',
    
    // PeerConnect Section
    'peerconnect.title': 'PeerConnect',
    'peerconnect.subtitle': 'Terhubung dengan teman sekelas dan dosen melalui platform komunikasi terintegrasi kami',
    'peerconnect.groupChat': 'Grup Chat',
    'peerconnect.groupChatDesc': 'Buat dan bergabung dengan grup chat untuk diskusi kelas, proyek kelompok, atau komunitas kampus.',
    'peerconnect.groupFeature1': 'Bagikan file dan dokumen penting',
    'peerconnect.groupFeature2': 'Diskusi real-time dengan anggota grup',
    'peerconnect.groupFeature3': 'Notifikasi untuk pesan penting',
    'peerconnect.privateChat': 'Private Chat',
    'peerconnect.privateChatDesc': 'Komunikasi langsung dan pribadi dengan teman sekelas atau dosen untuk diskusi yang lebih fokus.',
    'peerconnect.privateFeature1': 'Pesan end-to-end encryption',
    'peerconnect.privateFeature2': 'Bagikan file dan media secara aman',
    'peerconnect.privateFeature3': 'Status online untuk melihat ketersediaan',
    'peerconnect.videoCall': 'Video Call',
    'peerconnect.videoCallDesc': 'Lakukan panggilan video dengan kualitas tinggi untuk meeting online, konsultasi, atau belajar bersama.',
    'peerconnect.videoFeature1': 'Video HD dengan audio jernih',
    'peerconnect.videoFeature2': 'Screen sharing untuk presentasi',
    'peerconnect.videoFeature3': 'Record meeting untuk dokumentasi',

    // AI Campus Section
    'aicampus.title': 'AI Campus Chatbot',
    'aicampus.subtitle': 'Asisten virtual cerdas untuk menjawab pertanyaan seputar kampus',
    'aicampus.campusMode': 'Mode Kampus',
    'aicampus.campusModeDesc': 'Tanya tentang informasi kampus, KRS, gedung, dosen, beasiswa, dan segala hal terkait kampus',
    'aicampus.campusFeature1': 'Informasi KRS, mata kuliah, dan jadwal',
    'aicampus.campusFeature2': 'Data dosen, gedung, dan fasilitas kampus',
    'aicampus.campusFeature3': 'Info beasiswa dan program akademik',
    'aicampus.generalMode': 'Mode General',
    'aicampus.generalModeDesc': 'Tanya apapun! AI siap membantu menjawab pertanyaan umum, tugas, atau hal lainnya',
    'aicampus.generalFeature1': 'Bantuan mengerjakan tugas dan PR',
    'aicampus.generalFeature2': 'Penjelasan konsep dan materi pelajaran',
    'aicampus.generalFeature3': 'Pertanyaan umum tentang apapun',

    // Event Reminder Section
    'eventreminder.title': 'Event Recommender',
    'eventreminder.subtitle': 'Rekomendasi event kampus yang sesuai dengan minat dan kebutuhanmu',
    'eventreminder.recommendations': 'Rekomendasi Event',
    'eventreminder.recommendationsDesc': 'Dapatkan rekomendasi event kampus yang sesuai dengan minat dan kebutuhanmu',
    'eventreminder.feature1': 'Notifikasi acara berdasarkan preferensi',
    'eventreminder.feature2': 'Kalender terintegrasi untuk pelacakan',
    'eventreminder.feature3': 'Konfirmasi dan pendaftaran langsung',

    // Smart Schedule Section
    'smartschedule.title': 'Smart Schedule',
    'smartschedule.subtitle': 'Kelola jadwal kuliah, tugas, dan aktivitas kampus dengan cerdas',
    'smartschedule.optimization': 'Optimalisasi Jadwal',
    'smartschedule.optimizationDesc': 'Kelola dan optimalkan jadwal kuliah, tugas, dan aktivitas kampus dengan cerdas',
    'smartschedule.optimizationFeature1': 'Optimasi jadwal berbasis AI',
    'smartschedule.optimizationFeature2': 'Pengingat otomatis untuk tenggat waktu',
    'smartschedule.optimizationFeature3': 'Tampilan visual jadwal mingguan',
    'smartschedule.integration': 'Integrasi ke Kalender',
    'smartschedule.integrationDesc': 'Sinkronisasi jadwal dengan Kalender Google dan platform lainnya',
    'smartschedule.integrationFeature1': 'Sinkronisasi dengan Kalender Google',
    'smartschedule.integrationFeature2': 'Ekspor jadwal ke berbagai format',
    'smartschedule.integrationFeature3': 'Sinkronisasi otomatis secara real-time',

    // Task Manager Section
    'taskmanager.title': 'Task Manager',
    'taskmanager.subtitle': 'Kelola tugas kuliah dan proyek dengan sistem manajemen yang efektif',
    'taskmanager.manageTasks': 'Kelola Tugas',
    'taskmanager.manageTasksDesc': 'Kelola tugas kuliah dan proyek dengan sistem manajemen yang efektif',
    'taskmanager.feature1': 'Daftar tugas dengan sistem prioritas',
    'taskmanager.feature2': 'Pelacakan kemajuan untuk setiap tugas',
    'taskmanager.feature3': 'Kolaborasi tim untuk proyek kelompok',

    // Collaboration Section
    'collaboration.title': 'Project Collaboration',
    'collaboration.subtitle': 'Terhubung dengan teman sekelas dan dosen melalui platform komunikasi terintegrasi',
    'collaboration.project': 'Kolaborasi Project',
    'collaboration.projectDesc': 'Platform kolaborasi untuk proyek kelompok yang lebih produktif',
    'collaboration.feature1': 'Alat kolaborasi secara real-time',
    'collaboration.feature2': 'Berbagi file dan kontrol versi',
    'collaboration.feature3': 'Pembagian tugas untuk anggota tim',

    // Chat Interface
    'chat.welcome': 'AI CAMPUS CHATBOT',
    'chat.subtitle': 'Asisten virtual cerdas untuk membantu menjawab semua pertanyaan seputar kampus',
    'chat.selectMode': 'Pilih Mode Chat',
    'chat.campusMode': 'Mode Kampus',
    'chat.campusModeDesc': 'Tanya tentang informasi kampus, KRS, gedung, dosen, beasiswa, dan kehidupan kampus',
    'chat.generalMode': 'Mode Umum',
    'chat.generalModeDesc': 'Tanya apapun: teknologi, sains, budaya, tips, resep, dan topik lainnya',
    'chat.challengeMode': 'Challenge Me',
    'chat.challengeModeDesc': 'AI akan menjadi oposisi dari pendapatmu untuk melatih kemampuan berpikir kritis dan berargumentasi',
    'chat.challengeModeSubtitle': 'Debate Mode - Latih Kemampuan Berargumentasi',
    'chat.selectUniversity': 'Pilih Universitas',
    'chat.yourUniversity': 'Universitas Kamu',
    'chat.selectUniversityPlaceholder': '-- Pilih Universitas --',
    'chat.loadingUniversity': 'Memuat data universitas dari profil...',
    'chat.loginToAutofill': '💡 Login dan isi profil untuk auto-fill universitas',
    'chat.selectQuestion': 'Pilih Pertanyaan',
    'chat.typeQuestion': 'Ketik Pertanyaan Apapun',
    'chat.generalModeNote': 'Mode umum - Tanyakan apapun yang ingin kamu ketahui',
    'chat.generalModePlaceholder': 'Contoh: Jelaskan tentang AI, Resep makanan sehat, Tips belajar efektif, dll.',
    'chat.startChat': 'Mulai Chat',
    'chat.answer': 'Jawaban',
    'chat.reset': 'Reset',
    'chat.aiAssistant': 'AI Assistant',
    'chat.generalModeLabel': 'Mode Umum',
    'chat.send': 'Kirim',
    'chat.generalModeTip': '💡 Mode Umum: Tanya apapun yang ingin kamu ketahui',
    'chat.campusModeTip': '💡 Tips: Tanya tentang KRS, gedung, dosen, beasiswa, atau kehidupan kampus',
    'chat.comingSoon': '🚧 Coming Soon!\n\nSaat ini AI Campus Navigator hanya tersedia untuk Universitas Sebelas Maret (UNS). Data untuk universitas lain sedang dalam proses pengembangan dan akan segera hadir.\n\nTerima kasih atas pengertiannya! 🙏',
    'chat.welcomeCampus': 'Halo! Saya AI Campus Navigator untuk',
    'chat.welcomeCampusEnd': 'Saya siap membantu menjawab pertanyaan Anda.',
    'chat.welcomeGeneral': 'Halo! Saya asisten AI yang siap membantu menjawab berbagai pertanyaan Anda.',
    'chat.welcomeChallenge': 'Halo! Selamat datang di mode Challenge Me! 🎯\n\nDi mode ini, saya akan menjadi oposisi dari pendapat kamu. Tujuannya adalah melatih kemampuan berpikir kritis dan berargumentasi kamu.\n\nSilakan beritahu saya isu atau topik apa yang ingin kita diskusikan hari ini?\n\nContoh topik:\n- "AI akan menggantikan semua pekerjaan manusia"\n- "Media sosial lebih banyak dampak negatifnya"\n- "Pendidikan online lebih efektif dari tatap muka"\n- Atau topik apapun yang ingin kamu bahas!\n\nSetelah kamu memberikan topik, saya akan mengambil posisi berlawanan dan kita bisa mulai berdiskusi.',
    'chat.error': 'Maaf, terjadi kesalahan. Silakan coba lagi.',
    'chat.alertSelectMode': 'Silakan pilih mode terlebih dahulu!',
    'chat.alertSelectUniversity': 'Silakan pilih universitas terlebih dahulu!',
    'chat.alertSelectQuestion': 'Silakan pilih atau ketik pertanyaan!',
    'chat.alertComingSoon': 'Coming Soon! Saat ini hanya tersedia untuk Universitas Sebelas Maret (UNS). Universitas lain akan segera hadir.',
    'chat.inputPlaceholderGeneral': 'Tanya apapun yang ingin kamu ketahui...',
    'chat.inputPlaceholderCampus': 'Ketik pertanyaan lanjutan tentang kampus...',
    'chat.inputPlaceholderChallenge': 'Ketik topik atau argumenmu...',
    'chat.challengeModeTip': '🎯 Challenge Mode: AI akan menantang argumenmu untuk melatih kemampuan berpikirmu',
    'chat.category.krs': 'KRS',
    'chat.category.gedung': 'Gedung',
    'chat.category.dosen': 'Dosen',
    'chat.category.beasiswa': 'Beasiswa',
    'chat.category.akademik': 'Akademik',
    'chat.category.ukm': 'UKM',
    'chat.question.krs': 'Bagaimana cara mengisi KRS?',
    'chat.question.library': 'Di mana lokasi perpustakaan pusat?',
    'chat.question.lecturer': 'Bagaimana cara mencari info dosen?',
    'chat.question.scholarship': 'Beasiswa apa saja yang tersedia?',
    'chat.question.schedule': 'Kapan jadwal UTS dan UAS?',
    'chat.question.organization': 'UKM apa saja yang ada?',

    // Event Recommender Section
    'events.title': 'EVENT RECOMMENDER',
    'events.subtitle': 'Temukan event kampus yang sesuai dengan minatmu!',
    'events.filterTitle': 'Filter Minat',
    'events.clearButton': 'Hapus',
    'events.searchButton': 'Cari Event',
    'events.searching': 'Mencari...',
    'events.analyzing': 'AI sedang menganalisis event yang cocok untukmu...',
    'events.noResults': 'Tidak Ada Event yang Cocok',
    'events.noResultsDesc': 'Coba pilih minat yang berbeda atau tunggu event baru!',
    'events.aiRecommendation': 'REKOMENDASI AI:',
    'events.allEventsTitle': 'SEMUA EVENT YANG TERSEDIA:',
    'events.allEventsDesc': 'Menampilkan {count} event yang tersedia. Pilih minat dan klik "Cari Event" untuk filter lebih spesifik.',
    'events.loadingTitle': 'Memuat Event...',
    'events.loadingDesc': 'Mengambil data event yang tersedia',
    'events.organizer': 'Penyelenggara',
    'events.quota': 'Kuota Peserta',
    'events.people': 'orang',
    'events.eventDescription': 'Deskripsi Event',
    'events.registrationFee': 'Biaya Pendaftaran: ',
    'events.registerNow': 'Daftar Sekarang',
    'events.whyMatch': '💡 Kenapa cocok untukmu: ',
    'events.errorMessage': 'Terjadi kesalahan. Silakan coba lagi.',
    'events.allEventsMessage': 'Menampilkan semua {count} event yang tersedia. Pilih minat untuk filter lebih spesifik.',

    // Event Interest Categories
    'events.interest.teknologi': 'Teknologi & IT',
    'events.interest.bisnis': 'Bisnis & Kewirausahaan',
    'events.interest.seni': 'Seni & Kreatif',
    'events.interest.sosial': 'Sosial & Volunteering',
    'events.interest.akademik': 'Akademik & Riset',
    'events.interest.olahraga': 'Olahraga & Kesehatan',
    'events.interest.leadership': 'Leadership & Organisasi',
    'events.interest.lingkungan': 'Lingkungan & Keberlanjutan',

    // Smart Schedule Builder Section
    'schedule.title': 'SMART SCHEDULE BUILDER',
    'schedule.subtitle': 'AI bantu atur jadwal kuliah dan kegiatanmu agar seimbang dan produktif',
    'schedule.tabs.input': 'INPUT JADWAL',
    'schedule.tabs.result': 'JADWAL OPTIMAL',
    'schedule.tabs.calendar': 'KALENDER',
    'schedule.courses.title': 'JADWAL KULIAH',
    'schedule.courses.count': 'Kuliah',
    'schedule.activities.title': 'KEGIATAN LAIN',
    'schedule.activities.count': 'Kegiatan',
    'schedule.mode.flexible': 'WAKTU FLEKSIBEL',
    'schedule.mode.flexibleDesc': 'AI tentukan waktu',
    'schedule.mode.specific': 'WAKTU SPESIFIK',
    'schedule.mode.specificDesc': 'Waktu ditentukan',
    'schedule.placeholders.courseName': 'Nama Mata Kuliah',
    'schedule.placeholders.activityName': 'Nama Kegiatan',
    'schedule.placeholders.location': 'Lokasi (opsional)',
    'schedule.placeholders.description': 'Keterangan (opsional)',
    'schedule.days.monday': 'Senin',
    'schedule.days.tuesday': 'Selasa',
    'schedule.days.wednesday': 'Rabu',
    'schedule.days.thursday': 'Kamis',
    'schedule.days.friday': 'Jumat',
    'schedule.days.saturday': 'Sabtu',
    'schedule.days.sunday': 'Minggu',
    'schedule.courseTypes.theory': 'Teori',
    'schedule.courseTypes.practicum': 'Praktikum',
    'schedule.courseTypes.lab': 'Lab',
    'schedule.courseTypes.seminar': 'Seminar',
    'schedule.labels.startTime': 'Jam Mulai',
    'schedule.labels.endTime': 'Jam Selesai',
    'schedule.durations.30min': '30 menit',
    'schedule.durations.1hour': '1 jam',
    'schedule.durations.1.5hours': '1.5 jam',
    'schedule.durations.2hours': '2 jam',
    'schedule.durations.3hours': '3 jam',
    'schedule.priorities.high': 'Tinggi',
    'schedule.priorities.medium': 'Sedang',
    'schedule.priorities.low': 'Rendah',
    'schedule.timing.anytime': 'Kapan saja',
    'schedule.timing.before12': 'Sebelum jam 12:00',
    'schedule.timing.before15': 'Sebelum jam 15:00',
    'schedule.timing.before18': 'Sebelum jam 18:00',
    'schedule.timing.before20': 'Sebelum jam 20:00',
    'schedule.buttons.addCourse': '+ TAMBAH KULIAH',
    'schedule.buttons.addActivity': '+ TAMBAH KEGIATAN',
    'schedule.buttons.generate': 'GENERATE JADWAL OPTIMAL DENGAN AI',
    'schedule.buttons.generating': 'AI SEDANG MENYUSUN JADWAL OPTIMAL...',
    'schedule.analysis.totalCourses': 'Total Kuliah',
    'schedule.analysis.totalActivities': 'Total Kegiatan',
    'schedule.analysis.studyPerDay': 'Belajar/Hari',
    'schedule.analysis.workload': 'Beban Kerja',
    'schedule.warnings.title': 'PERINGATAN',
    'schedule.weekly.title': 'JADWAL MINGGUAN OPTIMAL',
    'schedule.collapse.close': '▼ Tutup',
    'schedule.collapse.open': '▶ Lihat Jadwal',
    'schedule.empty.title': 'BELUM ADA JADWAL',
    'schedule.empty.description': 'Generate jadwal terlebih dahulu di tab Input Jadwal',
    'schedule.empty.button': 'KE INPUT JADWAL',
    'schedule.modal.addCourse': 'TAMBAH JADWAL KULIAH',
    'schedule.modal.addActivity': 'TAMBAH KEGIATAN',
    'schedule.flexible': 'Fleksibel',
    'schedule.minute': 'menit',
    'schedule.alerts.fillFields': 'Lengkapi semua field!',
    'schedule.alerts.activityNameRequired': 'Nama kegiatan harus diisi!',
    'schedule.alerts.selectDayTime': 'Pilih hari dan waktu untuk kegiatan!',
    'schedule.alerts.durationRequired': 'Durasi kegiatan harus diisi!',
    'schedule.alerts.minOneItem': 'Tambahkan minimal 1 jadwal kuliah atau kegiatan!',
    'schedule.alerts.error': 'Terjadi kesalahan',

    // Smart Task Manager Section
    'tasks.title': 'SMART TASK MANAGER',
    'tasks.subtitle': 'Kelola tugas dan deadline dengan sistem AI yang cerdas',
    'tasks.loading.auth': 'Memuat data autentikasi...',
    'tasks.loading.data': 'Mengambil data tasks...',
    'tasks.auth.loginRequired': 'Silakan login untuk menggunakan fitur ini',
    'tasks.auth.loginButton': 'Login',
    'tasks.form.title': 'Judul Tugas',
    'tasks.form.description': 'Deskripsi',
    'tasks.form.category': 'Mata Kuliah',
    'tasks.form.priority': 'Prioritas',
    'tasks.form.deadline': 'Deadline',
    'tasks.placeholders.title': 'Contoh: Mengerjakan PR Matematika',
    'tasks.placeholders.description': 'Detail tugas...',
    'tasks.placeholders.category': 'Contoh: Matematika, Fisika, dll',
    'tasks.placeholders.deadline': 'Pilih tanggal deadline',
    'tasks.priorities.low': 'Rendah',
    'tasks.priorities.medium': 'Sedang',
    'tasks.priorities.high': 'Tinggi',
    'tasks.status.pending': 'Pending',
    'tasks.status.completed': 'Selesai',
    'tasks.status.all': 'Semua',
    'tasks.buttons.addTask': 'Tambah Tugas',
    'tasks.buttons.save': 'Simpan',
    'tasks.buttons.cancel': 'Batal',
    'tasks.buttons.delete': 'Hapus',
    'tasks.buttons.edit': 'Edit',
    'tasks.buttons.complete': 'Selesai',
    'tasks.buttons.uncomplete': 'Belum Selesai',
    'tasks.buttons.close': 'Tutup',
    'tasks.filter.category': 'Semua Mata Kuliah',
    'tasks.filter.status': 'Status',
    'tasks.filter.all': 'Semua',
    'tasks.filter.selectCategory': 'Pilih Mata Kuliah',
    'tasks.ai.prioritizeTitle': 'Rekomendasi Prioritas Tugas',
    'tasks.ai.estimateTitle': 'Estimasi Waktu Pengerjaan',
    'tasks.ai.analyzing': 'AI sedang menganalisis tugas-tugas kamu...',
    'tasks.ai.wait': 'Mohon tunggu sebentar',
    'tasks.ai.noTasks': 'Belum ada tugas untuk dianalisis!',
    'tasks.ai.error': 'Maaf, terjadi kesalahan',
    'tasks.chart.completed': 'Selesai',
    'tasks.chart.pending': 'Pending',
    'tasks.chart.overdue': 'Terlambat',
    'tasks.chart.distribution': 'Distribusi Tugas',
    'tasks.chart.noData': 'Belum ada data untuk ditampilkan',
    'tasks.empty.title': 'Belum Ada Tugas',
    'tasks.empty.description': 'Klik tombol + untuk menambahkan tugas baru',
    'tasks.empty.button': 'Tambah Tugas Baru',
    'tasks.alerts.deleteConfirm': 'Yakin ingin menghapus tugas ini?',
    'tasks.alerts.addSuccess': 'Tugas berhasil ditambahkan!',
    'tasks.alerts.addError': 'Gagal menambahkan tugas. Silakan coba lagi.',
    'tasks.alerts.updateSuccess': 'Tugas berhasil diperbarui!',
    'tasks.alerts.updateError': 'Gagal mengubah status tugas. Silakan coba lagi.',
    'tasks.alerts.deleteSuccess': 'Tugas berhasil dihapus!',
    'tasks.alerts.deleteError': 'Gagal menghapus tugas. Silakan coba lagi.',
    'tasks.errors.fetch': 'Gagal memuat tugas',
    'tasks.errors.add': 'Gagal menambahkan tugas',
    'tasks.errors.update': 'Gagal memperbarui tugas',
    'tasks.errors.delete': 'Gagal menghapus tugas',
    'tasks.success.add': 'Tugas berhasil ditambahkan',
    'tasks.success.update': 'Tugas berhasil diperbarui',
    'tasks.success.delete': 'Tugas berhasil dihapus',
    'tasks.categories.all': 'Semua Kategori',
    'tasks.deadline.today': 'Hari Ini',
    'tasks.deadline.tomorrow': 'Besok',
    'tasks.deadline.thisWeek': 'Minggu Ini',
    'tasks.deadline.overdue': 'Terlambat',
    'tasks.stats.total': 'Total',
    'tasks.stats.completed': 'Selesai',
    'tasks.stats.pending': 'Pending',
    'tasks.stats.overdue': 'Terlambat',
    'tasks.stats.statistics': 'Statistik',
    'tasks.stats.progress': 'Progress Keseluruhan',
    'tasks.stats.completionRate': 'Completion Rate',
    'tasks.stats.categoryBreakdown': 'Tugas per Mata Kuliah',
    'tasks.stats.noCategory': 'Belum ada kategori',
    'tasks.stats.noCategoryDesc': 'Tambahkan tugas untuk melihat statistik',
    'tasks.modal.addTitle': 'Tambah Tugas Baru',
    'tasks.modal.editTitle': 'Edit Tugas',
    'tasks.count': 'tugas',

    // Project Collaboration Section
    'projects.title': 'Project Collaboration Hub',
    'projects.subtitle': 'Temukan proyek menarik atau buat proyek Anda sendiri. Kolaborasi dengan talenta terbaik untuk mewujudkan ide-ide hebat!',

    // Tabs
    'projects.tabs.all': 'Semua Project',
    'projects.tabs.myProjects': 'Project Saya',
    'projects.tabs.myApplications': 'Aplikasi Saya',

    // Stats
    'projects.stats.totalProjects': 'Total Projects',
    'projects.stats.openProjects': 'Open Projects',
    'projects.stats.activeCollaborators': 'Active Collaborators',

    // Status
    'projects.status.all': 'Semua Status',
    'projects.status.open': 'Open',
    'projects.status.inProgress': 'In Progress',
    'projects.status.completed': 'Completed',
    'projects.status.cancelled': 'Cancelled',

    // Filter
    'projects.filter.status': 'Filter Status:',

    // Buttons
    'projects.buttons.createProject': 'Buat Project',
    'projects.buttons.apply': 'Apply ke Project',
    'projects.buttons.viewDetails': 'Lihat Detail',
    'projects.buttons.edit': 'Edit',
    'projects.buttons.delete': 'Hapus',
    'projects.buttons.save': 'Simpan',
    'projects.buttons.cancel': 'Batal',
    'projects.buttons.close': 'Tutup',
    'projects.buttons.submit': 'Kirim Aplikasi',
    'projects.buttons.approve': 'Accept',
    'projects.buttons.reject': 'Reject',
    'projects.buttons.manageApplications': 'Kelola Aplikasi',
    'projects.buttons.updateProgress': 'Update Progress',
    'projects.buttons.saveProgress': 'Save Progress',
    'projects.buttons.saving': 'Saving...',
    'projects.buttons.submitting': 'Mengirim...',
    'projects.buttons.creating': 'Membuat...',
    'projects.buttons.addRole': 'Tambah Role',

    // Card Labels
    'projects.card.members': 'Collaborators',
    'projects.card.roles': 'Roles',
    'projects.card.deadline': 'Deadline:',
    'projects.card.progress': 'Progress',
    'projects.card.created': 'Created',
    'projects.card.more': 'more',
    'projects.card.filled': 'filled',

    // Detail Modal
    'projects.detail.title': 'Deskripsi Project',
    'projects.detail.rolesNeeded': 'Role yang Dibutuhkan',
    'projects.detail.roleFilled': 'Role sudah terpenuhi',
    'projects.detail.yourApplications': 'Aplikasi Anda',
    'projects.detail.by': 'By',
    'projects.detail.collaborators': 'Collaborators',
    'projects.detail.applications': 'Applications',

    // Create Project Modal
    'projects.create.title': 'Buat Project Baru',
    'projects.create.projectTitle': 'Judul Project',
    'projects.create.description': 'Deskripsi Project',
    'projects.create.deadline': 'Deadline (Opsional)',
    'projects.create.maxCollaborators': 'Max Collaborators',
    'projects.create.rolesNeeded': 'Role yang Dibutuhkan',
    'projects.create.roleName': 'Nama Role',
    'projects.create.roleDescription': 'Deskripsi (Opsional)',
    'projects.create.roleCount': 'Jumlah Dibutuhkan',
    'projects.create.roleNumber': 'Role #',

    // Apply Modal
    'projects.apply.title': 'Apply ke Project',
    'projects.apply.selectRole': 'Pilih Role',
    'projects.apply.selectRolePlaceholder': '-- Pilih Role --',
    'projects.apply.message': 'Pesan (Opsional)',
    'projects.apply.allRolesFilled': 'Semua role sudah terpenuhi',

    // Manage Applications Modal
    'projects.manage.title': 'Kelola Aplikasi',
    'projects.manage.pending': 'Pending',
    'projects.manage.accepted': 'Accepted',
    'projects.manage.rejected': 'Rejected',
    'projects.manage.noApplications': 'Tidak ada aplikasi',
    'projects.manage.filterStatus': 'Filter Status:',
    'projects.manage.all': 'Semua',

    // Progress Slider
    'projects.progress.title': 'Project Progress',
    'projects.progress.setProgress': 'Set Progress:',
    'projects.progress.updateButton': 'Update Progress',
    'projects.progress.notification': 'You updated your progress to',

    // Placeholders
    'projects.placeholders.projectTitle': 'Contoh: Website E-Commerce untuk UMKM',
    'projects.placeholders.description': 'Jelaskan project Anda secara detail...',
    'projects.placeholders.maxCollaborators': 'Masukkan jumlah maksimal',
    'projects.placeholders.roleName': 'Contoh: Frontend Developer, UI/UX Designer',
    'projects.placeholders.roleDescription': 'Jelaskan requirement role ini',
    'projects.placeholders.message': 'Jelaskan mengapa Anda cocok untuk role ini...',

    // Alerts & Messages
    'projects.alerts.selectRole': 'Pilih role yang ingin Anda apply',
    'projects.alerts.alreadyApplied': 'Anda sudah apply untuk role ini',
    'projects.alerts.applyFailed': 'Gagal mengirim aplikasi',
    'projects.alerts.projectTitleRequired': 'Judul project harus diisi',
    'projects.alerts.descriptionRequired': 'Deskripsi project harus diisi',
    'projects.alerts.maxCollaboratorsRequired': 'Max collaborators harus diisi',
    'projects.alerts.minOneRole': 'Minimal tambahkan 1 role yang dibutuhkan',
    'projects.alerts.createFailed': 'Gagal membuat project',
    'projects.alerts.updateFailed': 'Failed to update status',
    'projects.alerts.updateProgressFailed': 'Failed to update progress',

    // Empty States
    'projects.empty.noProjects': 'Belum ada project tersedia',
    'projects.empty.noProjectsDesc': 'Jadilah yang pertama membuat project!',
    'projects.empty.noMyProjects': 'Anda belum membuat project',
    'projects.empty.noMyProjectsDesc': 'Mulai buat project pertama Anda!',
    'projects.empty.noApplications': 'Anda belum apply ke project manapun',
    'projects.empty.noApplicationsDesc': 'Mulai eksplorasi dan apply ke project yang menarik!',

    // Loading
    'projects.loading': 'Memuat...',

    // Application Status Messages
    'projects.application.accepted': 'Selamat! Aplikasi Anda diterima. Anda sekarang bagian dari project ini.',
    'projects.application.rejected': 'Aplikasi Anda ditolak. Jangan berkecil hati, coba apply ke project lain!',
    'projects.application.pending': 'Aplikasi Anda sedang direview oleh initiator project.',

    // Other Labels
    'projects.labels.applied': 'Applied',
    'projects.labels.projectStatus': 'Project Status',
    'projects.labels.initiator': 'Initiator',
    'projects.labels.organizer': 'Penyelenggara',
  },
  en: {
    // Navigation
    'nav.pages': 'Pages',
    'nav.features': 'Features',
    'nav.peerconnect': 'PeerConnect',
    'nav.aboutUs': 'About Us',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Page titles
    'page.aiCampusGuide': 'AI Campus Guide',
    'page.eventRecommender': 'Event Recommender',
    'page.smartScheduleBuilder': 'Smart Schedule Builder',
    'page.peerConnectAI': 'Peer Connect AI',
    'page.smartTaskManager': 'Smart Task Manager',
    'page.projectCollaboration': 'Project Collaboration',
    
    // Hero Section
    'hero.empowering': 'Empowering Students with AI',
    'hero.companion': 'Your Smart Campus Companion',
    'hero.navigate': 'Navigate Campus Life Seamlessly',
    'hero.learn': 'Learn Smarter, Connect Better, Achieve More',
    
    // Features Section
    'features.title': 'Our Featured Features',
    'features.subtitle': 'Discover various innovative features specifically designed to enhance your campus experience',
    'features.aiCampusGuide': 'AI Campus Guide Chatbot',
    'features.aiCampusGuideDesc': 'Ask anything about campus! From how to fill KRS, building locations, lecturer info, to scholarship procedures. AI is ready to help 24/7.',
    'features.eventRecommender': 'Event Recommender',
    'features.eventRecommenderDesc': 'Get activity recommendations that match your interests! Seminars, competitions, student organizations, volunteering - all tailored for you.',
    'features.smartSchedule': 'Smart Schedule Builder',
    'features.smartScheduleDesc': 'AI helps arrange your class and activity schedule to be balanced. No more schedule conflicts or activity overload!',
    'features.peerConnect': 'Peer Connect AI',
    'features.peerConnectDesc': 'Find friends or mentors with similar interests! AI matches you with the right people to grow together.',
    'features.taskManager': 'Smart Task Manager',
    'features.taskManagerDesc': 'Manage tasks and deadlines easily! AI will prioritize your tasks and remind you before it\'s too late.',
    'features.projectCollab': 'Project Collaboration',
    'features.projectCollabDesc': 'Project collaboration becomes easier! Create teams, share tasks, and monitor progress together in one platform.',
    
    // Stats
    'stats.activeStudents': 'Active Students',
    'stats.eventsPerMonth': 'Events per Month',
    'stats.userSatisfaction': 'User Satisfaction',
    'stats.aiSupport': 'AI Support',
    
    // FAQ Section
    'faq.title': 'FAQs',
    'faq.welcome': 'Hello! I am the AI Assistant for the AICAMPUS web application. I am ready to help answer questions about the AICAMPUS application. Please select a quick question below or type your own question!',
    'faq.q1': 'Do I need to login to use AICAMPUS features?',
    'faq.a1': 'Yes, you need to create an account and login to use all AICAMPUS features. The registration process is very easy and fast - just use your campus email or login with a Google account. After logging in, you can immediately enjoy all features like AI Campus Guide, Event Recommender, Smart Schedule Builder, and others.',
    'faq.q2': 'How to use the AI Campus Guide feature?',
    'faq.a2': 'After logging in and setting up your profile where you enter your university or you can directly enter without setting up a profile, click the "AI Campus Guide" page in the dashboard. Click your question about campus or you can ask questions other than those in the general mode options, then AI will provide accurate answers.',
    'faq.q3': 'How to use Smart Schedule Builder?',
    'faq.a3': 'Click the "Smart Schedule Builder" menu, then enter your courses and activities by pressing the "Class Schedule" or "Other Activities" button. Fill in details like name, day, and time. After adding all schedules, click "Generate Optimal Schedule" and AI will arrange the best schedule that avoids conflicts and maximizes your rest time. This is also integrated with Google Calendar.',
    'faq.q4': 'How to use Event Recommender?',
    'faq.a4': 'Open the "Event Recommender" menu in the dashboard. The first time, you are shown existing events, but if you want to follow a specific event, you can use the filters on the left side. After that, the system will automatically recommend suitable events. You can register directly, or view event details like time, location, and requirements.',
    'faq.q5': 'How to use Peer Connect AI?',
    'faq.a5': 'Go to the "Peer Connect AI" menu and complete your profile (major, interests, skills, goals). AI will match you with compatible students or mentors. You can see match profiles, send connect requests, and start communicating. This feature is very useful for finding study partners or mentors for career guidance and can also use video calls.',
    'faq.q6': 'How to use Smart Task Manager?',
    'faq.a6': 'Open the "Smart Task Manager" menu and add your tasks with their respective deadlines. AI will automatically prioritize tasks based on urgency level and deadline. You will receive reminder notifications before deadlines, and can track task progress in one easy-to-understand dashboard.',
    'faq.q7': 'How to use Project Collaboration?',
    'faq.a7': 'Click "Project Collaboration", create a new project, and invite your team members. You can assign tasks to each member, upload project files, do real-time collaboration, and track project progress.',
    'faq.q8': 'Can AI Campus Guide answer all questions about campus?',
    'faq.a8': 'Yes! Our AI Campus Guide is designed to answer various questions about campus life, from how to fill KRS, building locations, lecturer info, scholarship procedures, class schedules, to student organization information. Our AI continues to learn and is updated to provide accurate and relevant answers.',
    'faq.q9': 'Is my personal data secure?',
    'faq.a9': 'Your data security is our top priority. All personal information is encrypted and stored with enterprise-level security standards. We will not share your data with third parties without your permission. Our platform also complies with applicable data protection regulations.',
    'faq.q10': 'Is this service paid?',
    'faq.a10': 'We provide a free package with basic features that are already very complete to support your campus life. For premium features like priority mentoring, in-depth analytics, and more personalized recommendations, subscription packages are available at affordable prices specifically for students.',
    
    // PeerConnect Section
    'peerconnect.title': 'PeerConnect',
    'peerconnect.subtitle': 'Connect with classmates and lecturers through our integrated communication platform',
    'peerconnect.groupChat': 'Group Chat',
    'peerconnect.groupChatDesc': 'Create and join group chats for class discussions, group projects, or campus communities.',
    'peerconnect.groupFeature1': 'Share important files and documents',
    'peerconnect.groupFeature2': 'Real-time discussions with group members',
    'peerconnect.groupFeature3': 'Notifications for important messages',
    'peerconnect.privateChat': 'Private Chat',
    'peerconnect.privateChatDesc': 'Direct and personal communication with classmates or lecturers for more focused discussions.',
    'peerconnect.privateFeature1': 'End-to-end encrypted messages',
    'peerconnect.privateFeature2': 'Secure file and media sharing',
    'peerconnect.privateFeature3': 'Online status to see availability',
    'peerconnect.videoCall': 'Video Call',
    'peerconnect.videoCallDesc': 'Make high-quality video calls for online meetings, consultations, or study sessions together.',
    'peerconnect.videoFeature1': 'HD video with clear audio',
    'peerconnect.videoFeature2': 'Screen sharing for presentations',
    'peerconnect.videoFeature3': 'Record meetings for documentation',

    // AI Campus Section
    'aicampus.title': 'AI Campus Chatbot',
    'aicampus.subtitle': 'Smart virtual assistant to answer questions about campus',
    'aicampus.campusMode': 'Campus Mode',
    'aicampus.campusModeDesc': 'Ask about campus information, KRS, buildings, lecturers, scholarships, and everything related to campus',
    'aicampus.campusFeature1': 'KRS information, courses, and schedules',
    'aicampus.campusFeature2': 'Lecturer data, buildings, and campus facilities',
    'aicampus.campusFeature3': 'Scholarship and academic program info',
    'aicampus.generalMode': 'General Mode',
    'aicampus.generalModeDesc': 'Ask anything! AI is ready to help answer general questions, assignments, or anything else',
    'aicampus.generalFeature1': 'Help with homework and assignments',
    'aicampus.generalFeature2': 'Explanation of concepts and learning materials',
    'aicampus.generalFeature3': 'General questions about anything',

    // Event Reminder Section
    'eventreminder.title': 'Event Recommender',
    'eventreminder.subtitle': 'Campus event recommendations that match your interests and needs',
    'eventreminder.recommendations': 'Event Recommendations',
    'eventreminder.recommendationsDesc': 'Get campus event recommendations that match your interests and needs',
    'eventreminder.feature1': 'Event notifications based on preferences',
    'eventreminder.feature2': 'Integrated calendar for tracking',
    'eventreminder.feature3': 'Direct confirmation and registration',

    // Smart Schedule Section
    'smartschedule.title': 'Smart Schedule',
    'smartschedule.subtitle': 'Manage class schedules, assignments, and campus activities smartly',
    'smartschedule.optimization': 'Schedule Optimization',
    'smartschedule.optimizationDesc': 'Manage and optimize class schedules, assignments, and campus activities smartly',
    'smartschedule.optimizationFeature1': 'AI-based schedule optimization',
    'smartschedule.optimizationFeature2': 'Automatic reminders for deadlines',
    'smartschedule.optimizationFeature3': 'Visual display of weekly schedule',
    'smartschedule.integration': 'Calendar Integration',
    'smartschedule.integrationDesc': 'Synchronize schedule with Google Calendar and other platforms',
    'smartschedule.integrationFeature1': 'Synchronization with Google Calendar',
    'smartschedule.integrationFeature2': 'Export schedule to various formats',
    'smartschedule.integrationFeature3': 'Automatic real-time synchronization',

    // Task Manager Section
    'taskmanager.title': 'Task Manager',
    'taskmanager.subtitle': 'Manage college assignments and projects with an effective management system',
    'taskmanager.manageTasks': 'Manage Tasks',
    'taskmanager.manageTasksDesc': 'Manage college assignments and projects with an effective management system',
    'taskmanager.feature1': 'Task list with priority system',
    'taskmanager.feature2': 'Progress tracking for each task',
    'taskmanager.feature3': 'Team collaboration for group projects',

    // Collaboration Section
    'collaboration.title': 'Project Collaboration',
    'collaboration.subtitle': 'Connect with classmates and lecturers through an integrated communication platform',
    'collaboration.project': 'Project Collaboration',
    'collaboration.projectDesc': 'Collaboration platform for more productive group projects',
    'collaboration.feature1': 'Real-time collaboration tools',
    'collaboration.feature2': 'File sharing and version control',
    'collaboration.feature3': 'Task assignment for team members',

    // Chat Interface
    'chat.welcome': 'AI CAMPUS CHATBOT',
    'chat.subtitle': 'Smart virtual assistant to help answer all questions about campus',
    'chat.selectMode': 'Select Chat Mode',
    'chat.campusMode': 'Campus Mode',
    'chat.campusModeDesc': 'Ask about campus information, KRS, buildings, lecturers, scholarships, and campus life',
    'chat.generalMode': 'General Mode',
    'chat.generalModeDesc': 'Ask anything: technology, science, culture, tips, recipes, and other topics',
    'chat.challengeMode': 'Challenge Me',
    'chat.challengeModeDesc': 'AI will oppose your opinion to train your critical thinking and argumentation skills',
    'chat.challengeModeSubtitle': 'Debate Mode - Train Your Argumentation Skills',
    'chat.selectUniversity': 'Select University',
    'chat.yourUniversity': 'Your University',
    'chat.selectUniversityPlaceholder': '-- Select University --',
    'chat.loadingUniversity': 'Loading university data from profile...',
    'chat.loginToAutofill': '💡 Login and fill profile to auto-fill university',
    'chat.selectQuestion': 'Select Question',
    'chat.typeQuestion': 'Type Any Question',
    'chat.generalModeNote': 'General mode - Ask anything you want to know',
    'chat.generalModePlaceholder': 'Example: Explain about AI, Healthy food recipes, Effective study tips, etc.',
    'chat.startChat': 'Start Chat',
    'chat.answer': 'Answer',
    'chat.reset': 'Reset',
    'chat.aiAssistant': 'AI Assistant',
    'chat.generalModeLabel': 'General Mode',
    'chat.send': 'Send',
    'chat.generalModeTip': '💡 General Mode: Ask anything you want to know',
    'chat.campusModeTip': '💡 Tips: Ask about KRS, buildings, lecturers, scholarships, or campus life',
    'chat.comingSoon': '🚧 Coming Soon!\n\nCurrently AI Campus Navigator is only available for Sebelas Maret University (UNS). Data for other universities is under development and will be available soon.\n\nThank you for your understanding! 🙏',
    'chat.welcomeCampus': 'Hello! I am AI Campus Navigator for',
    'chat.welcomeCampusEnd': 'I am ready to help answer your questions.',
    'chat.welcomeGeneral': 'Hello! I am an AI assistant ready to help answer your various questions.',
    'chat.welcomeChallenge': 'Hello! Welcome to Challenge Me mode! 🎯\n\nIn this mode, I will oppose your opinion. The goal is to train your critical thinking and argumentation skills.\n\nPlease tell me what issue or topic you would like to discuss today?\n\nExample topics:\n- "AI will replace all human jobs"\n- "Social media has more negative impacts"\n- "Online education is more effective than face-to-face"\n- Or any topic you want to discuss!\n\nOnce you provide the topic, I will take the opposing position and we can start the discussion.',
    'chat.error': 'Sorry, an error occurred. Please try again.',
    'chat.alertSelectMode': 'Please select a mode first!',
    'chat.alertSelectUniversity': 'Please select a university first!',
    'chat.alertSelectQuestion': 'Please select or type a question!',
    'chat.alertComingSoon': 'Coming Soon! Currently only available for Sebelas Maret University (UNS). Other universities will be available soon.',
    'chat.inputPlaceholderGeneral': 'Ask anything you want to know...',
    'chat.inputPlaceholderCampus': 'Type follow-up questions about campus...',
    'chat.inputPlaceholderChallenge': 'Type your topic or argument...',
    'chat.challengeModeTip': '🎯 Challenge Mode: AI will challenge your arguments to train your thinking skills',
    'chat.category.krs': 'KRS',
    'chat.category.gedung': 'Building',
    'chat.category.dosen': 'Lecturer',
    'chat.category.beasiswa': 'Scholarship',
    'chat.category.akademik': 'Academic',
    'chat.category.ukm': 'Student Organization',
    'chat.question.krs': 'How to fill KRS?',
    'chat.question.library': 'Where is the central library located?',
    'chat.question.lecturer': 'How to find lecturer information?',
    'chat.question.scholarship': 'What scholarships are available?',
    'chat.question.schedule': 'When is the midterm and final exam schedule?',
    'chat.question.organization': 'What student organizations are available?',

    // Event Recommender Section
    'events.title': 'EVENT RECOMMENDER',
    'events.subtitle': 'Find campus events that match your interests!',
    'events.filterTitle': 'Interest Filter',
    'events.clearButton': 'Clear',
    'events.searchButton': 'Search Events',
    'events.searching': 'Searching...',
    'events.analyzing': 'AI is analyzing events that match you...',
    'events.noResults': 'No Matching Events',
    'events.noResultsDesc': 'Try selecting different interests or wait for new events!',
    'events.aiRecommendation': 'AI RECOMMENDATION:',
    'events.allEventsTitle': 'ALL AVAILABLE EVENTS:',
    'events.allEventsDesc': 'Showing {count} available events. Select interests and click "Search Events" for more specific filters.',
    'events.loadingTitle': 'Loading Events...',
    'events.loadingDesc': 'Retrieving available event data',
    'events.organizer': 'Organizer',
    'events.quota': 'Participant Quota',
    'events.people': 'people',
    'events.eventDescription': 'Event Description',
    'events.registrationFee': 'Registration Fee: ',
    'events.registerNow': 'Register Now',
    'events.whyMatch': '💡 Why it matches you: ',
    'events.errorMessage': 'An error occurred. Please try again.',
    'events.allEventsMessage': 'Showing all {count} available events. Select interests for more specific filters.',

    // Event Interest Categories
    'events.interest.teknologi': 'Technology & IT',
    'events.interest.bisnis': 'Business & Entrepreneurship',
    'events.interest.seni': 'Art & Creative',
    'events.interest.sosial': 'Social & Volunteering',
    'events.interest.akademik': 'Academic & Research',
    'events.interest.olahraga': 'Sports & Health',
    'events.interest.leadership': 'Leadership & Organization',
    'events.interest.lingkungan': 'Environment & Sustainability',

    // Smart Schedule Builder Section
    'schedule.title': 'SMART SCHEDULE BUILDER',
    'schedule.subtitle': 'AI helps organize your class and activity schedule to be balanced and productive',
    'schedule.tabs.input': 'INPUT SCHEDULE',
    'schedule.tabs.result': 'OPTIMAL SCHEDULE',
    'schedule.tabs.calendar': 'CALENDAR',
    'schedule.courses.title': 'CLASS SCHEDULE',
    'schedule.courses.count': 'Classes',
    'schedule.activities.title': 'OTHER ACTIVITIES',
    'schedule.activities.count': 'Activities',
    'schedule.mode.flexible': 'FLEXIBLE TIME',
    'schedule.mode.flexibleDesc': 'AI determines time',
    'schedule.mode.specific': 'SPECIFIC TIME',
    'schedule.mode.specificDesc': 'Time specified',
    'schedule.placeholders.courseName': 'Course Name',
    'schedule.placeholders.activityName': 'Activity Name',
    'schedule.placeholders.location': 'Location (optional)',
    'schedule.placeholders.description': 'Description (optional)',
    'schedule.days.monday': 'Monday',
    'schedule.days.tuesday': 'Tuesday',
    'schedule.days.wednesday': 'Wednesday',
    'schedule.days.thursday': 'Thursday',
    'schedule.days.friday': 'Friday',
    'schedule.days.saturday': 'Saturday',
    'schedule.days.sunday': 'Sunday',
    'schedule.courseTypes.theory': 'Theory',
    'schedule.courseTypes.practicum': 'Practicum',
    'schedule.courseTypes.lab': 'Lab',
    'schedule.courseTypes.seminar': 'Seminar',
    'schedule.labels.startTime': 'Start Time',
    'schedule.labels.endTime': 'End Time',
    'schedule.durations.30min': '30 minutes',
    'schedule.durations.1hour': '1 hour',
    'schedule.durations.1.5hours': '1.5 hours',
    'schedule.durations.2hours': '2 hours',
    'schedule.durations.3hours': '3 hours',
    'schedule.priorities.high': 'High',
    'schedule.priorities.medium': 'Medium',
    'schedule.priorities.low': 'Low',
    'schedule.timing.anytime': 'Anytime',
    'schedule.timing.before12': 'Before 12:00',
    'schedule.timing.before15': 'Before 15:00',
    'schedule.timing.before18': 'Before 18:00',
    'schedule.timing.before20': 'Before 20:00',
    'schedule.buttons.addCourse': '+ ADD CLASS',
    'schedule.buttons.addActivity': '+ ADD ACTIVITY',
    'schedule.buttons.generate': 'GENERATE OPTIMAL SCHEDULE WITH AI',
    'schedule.buttons.generating': 'AI IS CREATING OPTIMAL SCHEDULE...',
    'schedule.analysis.totalCourses': 'Total Classes',
    'schedule.analysis.totalActivities': 'Total Activities',
    'schedule.analysis.studyPerDay': 'Study/Day',
    'schedule.analysis.workload': 'Workload',
    'schedule.warnings.title': 'WARNINGS',
    'schedule.weekly.title': 'OPTIMAL WEEKLY SCHEDULE',
    'schedule.collapse.close': '▼ Close',
    'schedule.collapse.open': '▶ View Schedule',
    'schedule.empty.title': 'NO SCHEDULE YET',
    'schedule.empty.description': 'Generate schedule first in the Input Schedule tab',
    'schedule.empty.button': 'GO TO INPUT SCHEDULE',
    'schedule.modal.addCourse': 'ADD CLASS SCHEDULE',
    'schedule.modal.addActivity': 'ADD ACTIVITY',
    'schedule.flexible': 'Flexible',
    'schedule.minute': 'minutes',
    'schedule.alerts.fillFields': 'Fill in all fields!',
    'schedule.alerts.activityNameRequired': 'Activity name must be filled!',
    'schedule.alerts.selectDayTime': 'Select day and time for activity!',
    'schedule.alerts.durationRequired': 'Activity duration must be filled!',
    'schedule.alerts.minOneItem': 'Add at least 1 class schedule or activity!',
    'schedule.alerts.error': 'An error occurred',

    // Smart Task Manager Section
    'tasks.title': 'SMART TASK MANAGER',
    'tasks.subtitle': 'Manage tasks and deadlines with smart AI system',
    'tasks.loading.auth': 'Loading authentication data...',
    'tasks.loading.data': 'Retrieving tasks data...',
    'tasks.auth.loginRequired': 'Please login to use this feature',
    'tasks.auth.loginButton': 'Login',
    'tasks.form.title': 'Task Title',
    'tasks.form.description': 'Description',
    'tasks.form.category': 'Course',
    'tasks.form.priority': 'Priority',
    'tasks.form.deadline': 'Deadline',
    'tasks.placeholders.title': 'Example: Math Homework',
    'tasks.placeholders.description': 'Task details...',
    'tasks.placeholders.category': 'Example: Math, Physics, etc',
    'tasks.placeholders.deadline': 'Select deadline date',
    'tasks.priorities.low': 'Low',
    'tasks.priorities.medium': 'Medium',
    'tasks.priorities.high': 'High',
    'tasks.status.pending': 'Pending',
    'tasks.status.completed': 'Completed',
    'tasks.status.all': 'All',
    'tasks.buttons.addTask': 'Add Task',
    'tasks.buttons.save': 'Save',
    'tasks.buttons.cancel': 'Cancel',
    'tasks.buttons.delete': 'Delete',
    'tasks.buttons.edit': 'Edit',
    'tasks.buttons.complete': 'Complete',
    'tasks.buttons.uncomplete': 'Incomplete',
    'tasks.buttons.close': 'Close',
    'tasks.filter.category': 'All Courses',
    'tasks.filter.status': 'Status',
    'tasks.filter.all': 'All',
    'tasks.filter.selectCategory': 'Select Course',
    'tasks.ai.prioritizeTitle': 'Task Priority Recommendation',
    'tasks.ai.estimateTitle': 'Time Estimate',
    'tasks.ai.analyzing': 'AI is analyzing your tasks...',
    'tasks.ai.wait': 'Please wait a moment',
    'tasks.ai.noTasks': 'No tasks to analyze yet!',
    'tasks.ai.error': 'Sorry, an error occurred',
    'tasks.chart.completed': 'Completed',
    'tasks.chart.pending': 'Pending',
    'tasks.chart.overdue': 'Overdue',
    'tasks.chart.distribution': 'Task Distribution',
    'tasks.chart.noData': 'No data to display yet',
    'tasks.empty.title': 'No Tasks Yet',
    'tasks.empty.description': 'Click the + button to add a new task',
    'tasks.empty.button': 'Add New Task',
    'tasks.alerts.deleteConfirm': 'Are you sure you want to delete this task?',
    'tasks.alerts.addSuccess': 'Task successfully added!',
    'tasks.alerts.addError': 'Failed to add task. Please try again.',
    'tasks.alerts.updateSuccess': 'Task successfully updated!',
    'tasks.alerts.updateError': 'Failed to update task status. Please try again.',
    'tasks.alerts.deleteSuccess': 'Task successfully deleted!',
    'tasks.alerts.deleteError': 'Failed to delete task. Please try again.',
    'tasks.errors.fetch': 'Failed to load tasks',
    'tasks.errors.add': 'Failed to add task',
    'tasks.errors.update': 'Failed to update task',
    'tasks.errors.delete': 'Failed to delete task',
    'tasks.success.add': 'Task successfully added',
    'tasks.success.update': 'Task successfully updated',
    'tasks.success.delete': 'Task successfully deleted',
    'tasks.categories.all': 'All Categories',
    'tasks.deadline.today': 'Today',
    'tasks.deadline.tomorrow': 'Tomorrow',
    'tasks.deadline.thisWeek': 'This Week',
    'tasks.deadline.overdue': 'Overdue',
    'tasks.stats.total': 'Total',
    'tasks.stats.completed': 'Completed',
    'tasks.stats.pending': 'Pending',
    'tasks.stats.overdue': 'Overdue',
    'tasks.stats.statistics': 'Statistics',
    'tasks.stats.progress': 'Overall Progress',
    'tasks.stats.completionRate': 'Completion Rate',
    'tasks.stats.categoryBreakdown': 'Tasks per Course',
    'tasks.stats.noCategory': 'No categories yet',
    'tasks.stats.noCategoryDesc': 'Add tasks to view statistics',
    'tasks.modal.addTitle': 'Add New Task',
    'tasks.modal.editTitle': 'Edit Task',
    'tasks.count': 'tasks',

    // Project Collaboration Section
    'projects.title': 'Project Collaboration Hub',
    'projects.subtitle': 'Find interesting projects or create your own. Collaborate with the best talents to realize great ideas!',

    // Tabs
    'projects.tabs.all': 'All Projects',
    'projects.tabs.myProjects': 'My Projects',
    'projects.tabs.myApplications': 'My Applications',

    // Stats
    'projects.stats.totalProjects': 'Total Projects',
    'projects.stats.openProjects': 'Open Projects',
    'projects.stats.activeCollaborators': 'Active Collaborators',

    // Status
    'projects.status.all': 'All Status',
    'projects.status.open': 'Open',
    'projects.status.inProgress': 'In Progress',
    'projects.status.completed': 'Completed',
    'projects.status.cancelled': 'Cancelled',

    // Filter
    'projects.filter.status': 'Filter Status:',

    // Buttons
    'projects.buttons.createProject': 'Create Project',
    'projects.buttons.apply': 'Apply to Project',
    'projects.buttons.viewDetails': 'View Details',
    'projects.buttons.edit': 'Edit',
    'projects.buttons.delete': 'Delete',
    'projects.buttons.save': 'Save',
    'projects.buttons.cancel': 'Cancel',
    'projects.buttons.close': 'Close',
    'projects.buttons.submit': 'Submit Application',
    'projects.buttons.approve': 'Accept',
    'projects.buttons.reject': 'Reject',
    'projects.buttons.manageApplications': 'Manage Applications',
    'projects.buttons.updateProgress': 'Update Progress',
    'projects.buttons.saveProgress': 'Save Progress',
    'projects.buttons.saving': 'Saving...',
    'projects.buttons.submitting': 'Submitting...',
    'projects.buttons.creating': 'Creating...',
    'projects.buttons.addRole': 'Add Role',

    // Card Labels
    'projects.card.members': 'Collaborators',
    'projects.card.roles': 'Roles',
    'projects.card.deadline': 'Deadline:',
    'projects.card.progress': 'Progress',
    'projects.card.created': 'Created',
    'projects.card.more': 'more',
    'projects.card.filled': 'filled',

    // Detail Modal
    'projects.detail.title': 'Project Description',
    'projects.detail.rolesNeeded': 'Roles Needed',
    'projects.detail.roleFilled': 'Role is filled',
    'projects.detail.yourApplications': 'Your Applications',
    'projects.detail.by': 'By',
    'projects.detail.collaborators': 'Collaborators',
    'projects.detail.applications': 'Applications',

    // Create Project Modal
    'projects.create.title': 'Create New Project',
    'projects.create.projectTitle': 'Project Title',
    'projects.create.description': 'Project Description',
    'projects.create.deadline': 'Deadline (Optional)',
    'projects.create.maxCollaborators': 'Max Collaborators',
    'projects.create.rolesNeeded': 'Roles Needed',
    'projects.create.roleName': 'Role Name',
    'projects.create.roleDescription': 'Description (Optional)',
    'projects.create.roleCount': 'Required Count',
    'projects.create.roleNumber': 'Role #',

    // Apply Modal
    'projects.apply.title': 'Apply to Project',
    'projects.apply.selectRole': 'Select Role',
    'projects.apply.selectRolePlaceholder': '-- Select Role --',
    'projects.apply.message': 'Message (Optional)',
    'projects.apply.allRolesFilled': 'All roles are filled',

    // Manage Applications Modal
    'projects.manage.title': 'Manage Applications',
    'projects.manage.pending': 'Pending',
    'projects.manage.accepted': 'Accepted',
    'projects.manage.rejected': 'Rejected',
    'projects.manage.noApplications': 'No applications',
    'projects.manage.filterStatus': 'Filter Status:',
    'projects.manage.all': 'All',

    // Progress Slider
    'projects.progress.title': 'Project Progress',
    'projects.progress.setProgress': 'Set Progress:',
    'projects.progress.updateButton': 'Update Progress',
    'projects.progress.notification': 'You updated your progress to',

    // Placeholders
    'projects.placeholders.projectTitle': 'Example: E-Commerce Website for SMEs',
    'projects.placeholders.description': 'Explain your project in detail...',
    'projects.placeholders.maxCollaborators': 'Enter maximum number',
    'projects.placeholders.roleName': 'Example: Frontend Developer, UI/UX Designer',
    'projects.placeholders.roleDescription': 'Explain the requirements for this role',
    'projects.placeholders.message': 'Explain why you are suitable for this role...',

    // Alerts & Messages
    'projects.alerts.selectRole': 'Select the role you want to apply for',
    'projects.alerts.alreadyApplied': 'You have already applied for this role',
    'projects.alerts.applyFailed': 'Failed to submit application',
    'projects.alerts.projectTitleRequired': 'Project title is required',
    'projects.alerts.descriptionRequired': 'Project description is required',
    'projects.alerts.maxCollaboratorsRequired': 'Max collaborators is required',
    'projects.alerts.minOneRole': 'Add at least 1 required role',
    'projects.alerts.createFailed': 'Failed to create project',
    'projects.alerts.updateFailed': 'Failed to update status',
    'projects.alerts.updateProgressFailed': 'Failed to update progress',

    // Empty States
    'projects.empty.noProjects': 'No projects available yet',
    'projects.empty.noProjectsDesc': 'Be the first to create a project!',
    'projects.empty.noMyProjects': 'You have not created any projects yet',
    'projects.empty.noMyProjectsDesc': 'Start creating your first project!',
    'projects.empty.noApplications': 'You have not applied to any projects yet',
    'projects.empty.noApplicationsDesc': 'Start exploring and apply to interesting projects!',

    // Loading
    'projects.loading': 'Loading...',

    // Application Status Messages
    'projects.application.accepted': 'Congratulations! Your application has been accepted. You are now part of this project.',
    'projects.application.rejected': 'Your application was rejected. Don\'t be discouraged, try applying to other projects!',
    'projects.application.pending': 'Your application is being reviewed by the project initiator.',

    // Other Labels
    'projects.labels.applied': 'Applied',
    'projects.labels.projectStatus': 'Project Status',
    'projects.labels.initiator': 'Initiator',
    'projects.labels.organizer': 'Organizer',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize with localStorage value or default to 'id'
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'id' || savedLanguage === 'en')) {
        return savedLanguage;
      }
    }
    return 'id';
  });

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}